// <auto-generated />
using System;
using CityInfo.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CityInfo.DataAccess.Migrations
{
    [DbContext(typeof(CityInfoContext))]
    partial class CityInfoContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CityInfo.Contracts.Services.Entities.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description");

                    b.Property<int?>("ImageId");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.HasIndex("ImageId");

                    b.ToTable("Cities");

                    b.HasData(
                        new { Id = 1, Description = "Great park in the middle", Name = "New York City" },
                        new { Id = 2, Description = "the capital city and most populous municipality of the Commonwealth of Massachusetts in the United States.", Name = "Boston" },
                        new { Id = 3, Description = "It was founded by the Romans, who named it Londinium", Name = "London" }
                    );
                });

            modelBuilder.Entity("CityInfo.Contracts.Services.Entities.CityImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ContentType");

                    b.Property<byte[]>("Image");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("CityImages");
                });

            modelBuilder.Entity("CityInfo.Contracts.Services.Entities.PointOfInterest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CityId");

                    b.Property<string>("Description");

                    b.Property<string>("Name")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.ToTable("PointsOfInterest");

                    b.HasData(
                        new { Id = 10, CityId = 1, Description = "Welcome to point 10", Name = "Point 10" },
                        new { Id = 11, CityId = 1, Description = "Welcome to point 11", Name = "Point 11" },
                        new { Id = 12, CityId = 1, Description = "Welcome to point 12", Name = "Point 12" },
                        new { Id = 13, CityId = 2, Description = "Welcome to point 13", Name = "Point 13" },
                        new { Id = 14, CityId = 2, Description = "Welcome to point 14", Name = "Point 14" },
                        new { Id = 15, CityId = 2, Description = "Welcome to point 15", Name = "Point 15" },
                        new { Id = 16, CityId = 3, Description = "Welcome to point 16", Name = "Point 16" }
                    );
                });

            modelBuilder.Entity("CityInfo.Contracts.Services.Entities.Session", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Role");

                    b.HasKey("Id");

                    b.ToTable("Sessions");

                    b.HasData(
                        new { Id = new Guid("ab7f044d-03c5-4b4f-8420-64c5afb43f8d"), Role = "Admin" },
                        new { Id = new Guid("399e2aa6-88ad-439a-aaa8-cec92bf89cf0"), Role = "User" }
                    );
                });

            modelBuilder.Entity("CityInfo.Contracts.Services.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.Property<string>("Password");

                    b.Property<Guid?>("SessionId");

                    b.Property<string>("UserName");

                    b.HasKey("Id");

                    b.HasIndex("SessionId");

                    b.ToTable("Users");

                    b.HasData(
                        new { Id = 1, Name = "Juan", Password = "pwd", SessionId = new Guid("ab7f044d-03c5-4b4f-8420-64c5afb43f8d"), UserName = "juan89" },
                        new { Id = 2, Name = "Joe", Password = "pass", SessionId = new Guid("399e2aa6-88ad-439a-aaa8-cec92bf89cf0"), UserName = "joe123" }
                    );
                });

            modelBuilder.Entity("CityInfo.Contracts.Services.Entities.City", b =>
                {
                    b.HasOne("CityInfo.Contracts.Services.Entities.CityImage", "Image")
                        .WithMany()
                        .HasForeignKey("ImageId");
                });

            modelBuilder.Entity("CityInfo.Contracts.Services.Entities.PointOfInterest", b =>
                {
                    b.HasOne("CityInfo.Contracts.Services.Entities.City", "City")
                        .WithMany("PointsOfInterest")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("CityInfo.Contracts.Services.Entities.User", b =>
                {
                    b.HasOne("CityInfo.Contracts.Services.Entities.Session", "Session")
                        .WithMany()
                        .HasForeignKey("SessionId");
                });
#pragma warning restore 612, 618
        }
    }
}
